name: Github Pages

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cicd_pipeline:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Git clone odc home repository
        uses: actions/checkout@v1

      - name: Clean Install dependencies and Build
        run: |
          yarn install
          rm -rf build
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'build'

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

      - name: Print message on completion of gh-pages build
        run: echo "Build package deployed to gh-pages successfully."

      - name: Print message on completion of CD Pipeline
        run: echo "CD Pipeline finished successfully."
