name: Github Pages

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  yarn_install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn
  yarn_build:
    name: Build package
    runs-on: ubuntu-latest
    needs: yarn_install
    steps:
      - name: Build package
        run: yarn build
  gh_build:
    name: Build Github Pages
    runs-on: ubuntu-latest
    needs: [yarn_install, yarn_build]
    steps:
      - name: Build Github Pages
        run: gh-pages -d build
    
